### ISSUE TITLE
-lraylib not found with QTcreator on Windows

### ISSUE THREAD

**Issue by janderkkotlarski** [janderkkotlarski/raylib_testing#1]
QTcreator does not know how to link -lraylib on Windows, though everything relevant seems to be provided.

**Comment by janderkkotlarski** [comment]
![error_message](https://user-images.githubusercontent.com/13890380/106354078-7f74d100-62ef-11eb-93be-8438c4607ab1.jpg)

**Comment by richelbilderbeek** [comment]
Hmmm, without a Windows computer at hand, this would be hard for me to solve. 

For inspiration, I would use [this .pro file](https://github.com/CarmenIJsebaart/Sneek/blob/master/Sneek.pro#L20) as an example to get a library (in this case, SFML) linked under Windows. Note the use of this two types of slashes in paths :-/ .

Also, linking directly to the .a files is an option:

```
LIBS += C:/Boost/stage/lib/libboost_filesystem-mgw49-mt-1_59.a
```

Maybe I can help using Team Viewer? I would enjoy that!

**Comment by janderkkotlarski** [comment]
Linking to the .a files is not the problem.

I tried the other slash, does not work either.

What is Team Viewer and how do I use it?

**Comment by richelbilderbeek** [comment]
With Team Viewer I can access you computer as if it was I that was typing. You can see exactly what I am doing and can deny access any second. Want to try?

**Comment by richelbilderbeek** [comment]
AFAICS, this can be closed, as @janderkkotlarski got it working :partying_face: . Will do so :+1:
